### ISSUE TITLE
create api call to get list of cohorts

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/PAR#359]
includes:  learning how to use postman, and how to test spring api calls

how to demo:

- show working call in postman
- tests that demonstrate getting all current cohorts (with different cohorts from different cohortDatastores)

**Comment by vkumar825** [comment]
6/9/21

Worked on it for about an hour. 
- Tried a different approach to the problem, which turned out to be incorrect. I was looking at the wrong part of the JSON file which had me stuck. 

6/10/21
Learned the correct approach to this problem from the meeting. This took about half an hour to complete this task once I knew the right approach.
